### ISSUE TITLE
Feature Request - Firmware update with device isolated from internet

### ISSUE THREAD

**Issue by yahwehPT** [usnasoft/shellyscanner#1]
My shelly's (and all IOT's) are blocked from internet use, so for me to firmware update I have to allow the devices for internet use. It's possible to add an option to update these devices? Download the update to the computer running your program and update the firmware by URL, using the downloaded file. Maybe I'm not making much sense (english is not my first language) but something like this command line utility: https://github.com/ruimarinho/mota
thank you and great work

**Comment by usnasoft** [comment]
I could rather develop a simple CLI tool based on:
https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html

**Comment by Misiu** [comment]
Hi, @usnasoft I didn't want to create a new issue, so I'm commenting here.
A CLI tool is excellent for someone who has the knowledge but for regular users, a UI-based tool would be great.
Shelly Scanner is greater, so ideally it should allow downloading the latest version of firmware for every device, and then when inside an isolated network (without internet access) you could call OTA with files that were previously downloaded.

This functionality is available in https://github.com/bjuretko/shelly-offline-ota-update, but it would be great if it would be available in your tool.

Sadly I'm not a Java developer so I won't be able to help with implementing this, but please reconsider adding this functionality, maybe even use your CLI, but expose it via UI?

**Comment by usnasoft** [comment]
I will probably integrate [shellyscanner-fwupdater](https://github.com/usnasoft/shellyscanner-fwupdater) into ShellyScanner in the future. On the other hand I have no idea from where images can be downloaded apart from http://archive.shelly-tools.de/ that is not currentry up to date

**Comment by Misiu** [comment]
@usnasoft thank you for the reply :)
I think you can use https://api.shelly.cloud/files/firmware, this URL is specified in the tool (https://github.com/bjuretko/shelly-offline-ota-update/blob/master/server.js#L57) I linked previously.

**Comment by usnasoft** [comment]
sadly it seems https://api.shelly.cloud/files/firmware only report firmware for G1 devices;

**Comment by Misiu** [comment]
I just found this post:
https://www.facebook.com/groups/ShellyIoTCommunitySupport/posts/5595871290512189/?comment_id=5595884953844156&reply_comment_id=5597330240366294

https://updates.shelly.cloud/update/One
https://updates.shelly.cloud/update/OnePM
https://updates.shelly.cloud/update/Plus2PM
https://updates.shelly.cloud/update/PlusI4

**Comment by usnasoft** [comment]
thank you; this question:
"there were multiple threads about Gen2 firmware, the Team wrote a couple of times that they won't release the firmware because each device has an encryption key, and it matter of security. Did you try to flash the devices with those downloaded firmware files?"
without answer must be explored.
I'll do after 0.9.0 stable release
