### ISSUE TITLE
Multiple networks

### ISSUE THREAD

**Issue by rolfie23** [usnasoft/shellyscanner#10]
Good day,

Great application! Found it because my shelly ip's where organized but they where not anymore.... :') Now I have them in one view.

But I have my shelly's on 2 seperate networks (VLAN). So scanning in the app on the main network with "Full mDNS scan". Then go to IPscan restart the app and scan the other network for the other shelly's.

I have the networks 192.168.1.* and 192.168.3.*. Can you make it possible that at IP scan you van have mutiple IP ranges?

**Comment by usnasoft** [comment]
It's already on my personal wish list. Your request will raise its position near the top

**Comment by rolfie23** [comment]
> It's already on my personal wish list. Your request will raise its position near the top

Great! Let me know when its available! Close it for now, but you can still react on it if I'm right.

**Comment by usnasoft** [comment]
Done, function will be available on next release

**Comment by usnasoft** [comment]
new 1.0.6 beta release (now published) includes this evolution
