### ISSUE TITLE
Feature request - use device name when creating backups

### ISSUE THREAD

**Issue by gouthamravee** [usnasoft/shellyscanner#11]
Thank you so much for creating this awesome tool, its config backup is my primary use case for this tool. 

It would be a hell of a lot more useful if the config backup feature could create backups using the device's friendly name if it is set.

**Comment by usnasoft** [comment]
There are some reasons I use the device hostname:
- The hostname is unique for sure so no accidental overwrite is possible;
- if the friendly name changes I can always suggest the correct file name on restore;
- if you do restore after a reset (the most frequent case I think) you will not have the friendly name but I can still suggest the correct file name on restore.
Do I convinced you? If not I could work to an option on application settings in the future.

**Comment by gouthamravee** [comment]
You make damn solid points. 

The problem I have is trying to figure out which host names goes to what since all my shellies have host names like `shelly1pm-84CCA8B01B93` and `shelly1pm-B98798`, maybe that's a difference between gen 1 and newer gen devices. 

But I just realized that the restore process would use shelly scanner too, so I wouldn't have to worry about finding the correct shelly to restore to.
