### ISSUE TITLE
State of AP not restored

### ISSUE THREAD

**Issue by JoergGiencke** [usnasoft/shellyscanner#12]
Hi,

I have restored a reset Shelly +I4 from a backup and everything worked great - except - restoring the previous status of the access point. The restore ignores that the AP was switched off and leaves the access point at its default value of switched on.

```
  "wifi" : {
    "ap" : {
      "ssid" : "ShellyPlusI4-D8132AD261C8",
      "is_open" : true,
      "enable" : false, // IGNORED
      "range_extender" : {
        "enable" : false
      }
    },
```

**Comment by taulfsime** [comment]
Hello,

How did you restore a backup? We still doesn’t support such a thing.

Thanks,
Kristian Todorov

**Comment by usnasoft** [comment]
I'm on holiday for a few days now. I will check as soon as possible. Consider that the restore process does not change the parameters for the connection to which the device is currently connected. Is this the case? What version of Shelly Scanner are you using?

**Comment by JoergGiencke** [comment]
I'm using 1.0.7.

"Consider that the restore process does not change the parameters for the connection to which the device is currently connected."
Okay, that makes sense and if you know that, you can react accordingly. For me, the 'problem' is now solved.
Thank you!

**Comment by usnasoft** [comment]
I think I'll write a specific manual page for backup/restore
