### ISSUE TITLE
Shelly Plus Uni - not restoring part of configuration 

### ISSUE THREAD

**Issue by Grappa2020** [usnasoft/shellyscanner#15]
trying to restore same configuration to multiple Shelly Plus Uni devices and have some missing information. 
inputs, outputs settings and peripherals are missing the rest of the configuration is restore properly.
try with version : 1.1.0 and 1.1.1 beta

**Comment by usnasoft** [comment]
Shelly plus Uni is not fully supported. I have one but it seems to be faulty (I cannot even switch it on). I’ll buy an other one and implement the full model in the future. Antonio FlaccomioIl giorno 21 set 2024, alle ore 23:11, Grappa2020 ***@***.***> ha scritto:﻿
trying to restore same configuration to multiple Shelly Plus Uni devices and have some missing information.
inputs, outputs settings and peripherals are missing the rest of the configuration is restore properly.
try with version : 1.1.0 and 1.1.1 beta

**Comment by usnasoft** [comment]
Full support for plus UNI implemented from version 1.2.0 beta

**Comment by Grappa2020** [comment]
thanks a lot
