### ISSUE TITLE
Half of the buttons do not work

### ISSUE THREAD

**Issue by aly-fly** [usnasoft/shellyscanner#16]
Hi, thanks for the valuable work.
I have Win11 and JRE:
java 23.0.1 2024-10-15
Java(TM) SE Runtime Environment (build 23.0.1+11-39)
Java HotSpot(TM) 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
Run: double click on .jar file.

App runs fine, finds Shelly devices. 
Buttons Settings, About, Device info, Checklist, Notes do nothing. Pressing On/Off buttons have no effect.
Export and Backup button display Save dialog up, but the export file is not generated.
WebUI works. Reboot shows a dialog.

I read through FAQ and manual but couldn't find anything relevant.

**Comment by aly-fly** [comment]
After 5 application restarts now everything magically works. Weird.

**Comment by usnasoft** [comment]
Weird indeed. Should it happen again please run the application in "log mode" and post the results

**Comment by aly-fly** [comment]
I think that issue happened when I changed network interfaces while the program was open or actively scanning.
Didn't happen again recently.
