### ISSUE TITLE
[Feature Request] Self check for an update

### ISSUE THREAD

**Issue by Dtrieb** [usnasoft/shellyscanner#4]
Let the program self check, if there's an update.
Then redirect to the download page.

**Comment by usnasoft** [comment]
Probably I will implement this feature even if I have to overcome a taboo: the application will have to connect to internet

**Comment by thecode** [comment]
I would make it a button (`Check for Update`) so internet is not used unless user press the button

**Comment by Dtrieb** [comment]
> I would make it a button (`Check for Update`) so internet is not used unless user press the button

Good idea.

**Comment by usnasoft** [comment]
I'll add the suggested button on the the "information" dialog. Later, me and you, will take a decision on automatic check

**Comment by usnasoft** [comment]
next 1.0.0 beta will have the "check for updates" button on the "About" [?] dialog. Code already committed on dev branch

**Comment by usnasoft** [comment]
1.0.0 beta released (branch "jetty+"). Button is on "info" dialog. Maybe in the future we could implement an automatic check; let's test this by now

**Comment by usnasoft** [comment]
release 1.0.1 alpha finally introduces self check
