### ISSUE TITLE
TRV restore incomplete documentation

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [usnasoft/shellyscanner#6]
The documentation states: "Shelly TRV (restore incomplete)". Can we be a bit more detailed about that partial restore? What and maybe why. Thanks!

**Comment by usnasoft** [comment]
Hi,With regard to trv here you find all restored elements:- any element common to every Shelly device;- display settings;- temperature_offset;- ext_t_enabled.Why:I do not have a TRV. The development for this model has been carried out with help from some users. Any further improvement without local test is too complex. On the other hand, as far as I know, restore of calibration data would not be possible anywayAntonio FlaccomioAntonioIl giorno 16 set 2023, alle ore 00:10, Patrick ***@***.***> ha scritto:﻿
The documentation states: "Shelly TRV (restore incomplete)". Can we be a bit more detailed about that partial restore? What and maybe why. Thanks!

**Comment by patriiiiiiiiiick** [comment]
Thanks for the answer.
A part that would have been interesting to me is the schedule.
I understand it is complicated to put in place without a device to perform the tests.
